# Generated by Django 5.1.7 on 2025-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=8, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('frist_name', models.CharField(max_length=44)),
                ('last_name', models.CharField(max_length=44)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('dob', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
